---

- name: zshrc
  copy:
    src: .zshrc
    dest: ~/.zshrc
    force: true

- name: karabiner-elements
  template:
    src: karabiner.j2
    dest: ~/.config/karabiner/karabiner.json
    force: true
