---

- name: zshrc
  copy:
    src: .zshrc
    dest: ~/.zshrc
    force: true

- name: Ensure the direcrories exist
  file:
    path: "{{ item }}"
    state: directory
    with_items:
      - ~/.config/karabiner
      - ~/.config/ghostty


- name: karabiner-elements
  template:
    src: templates/karabiner.j2
    dest: ~/.config/karabiner/karabiner.json
    force: true

- name: starship
  copy:
    src: starship.toml
    dest: ~/.config/starship.toml
    force: true

- name: ghostty
  copy:
    src: ghostty.config
    dest: ~/.config/ghostty/config
    force: true
