---

- name: zshrc
  copy:
    src: .zshrc
    dest: ~/.zshrc
    force: true

- name: Ensure the target directory exists
  file:
    path: ~/.config
    state: directory

- name: karabiner-elements
  template:
    src: templates/karabiner.j2
    dest: ~/.config/karabiner/karabiner.json
    force: true

- name: starship
  copy:
    src: starship.toml
    dest: ~/.config/starship.toml
    force: true
