---
- name: Install homebrew packages
  homebrew:
    name: '{{ homebrew_packages }}'
    state: latest
  tags:
    - brew

- name: Install homebrew cask packages
  command: brew install {{ homebrew_cask_packages|join(" ") }}
  tags:
    - brew

- name: homebrew cleanup
  command: brew cleanup

- name: install zinit
  command: bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
