---
# - name: Update homebrew
#   homebrew:
#     name: git
#     state: latest
#     update_homebrew: true
#   tags:
#   - brew

- name: Install homebrew packages
  homebrew:
    name: '{{ homebrew_packages }}'
    state: latest
  tags:
  - brew

- name: Install homebrew cask packages
  command: brew install {{ homebrew_cask_packages|join(" ") }}
  tags:
  - brew

- name: homebrew cleanup
  command: brew cleanup
