---
- name: Install homebrew packages
  homebrew:
    name: '{{ homebrew_packages }}'
    state: latest
  tags:
    - brew

- name: Install homebrew cask packages
  command: brew install --cask {{ homebrew_cask_packages|join(" ") }}
  tags:
    - brew

- name: homebrew cleanup
  command: brew cleanup
